version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 1987
      MYSQL_DATABASE: api
      MYSQL_USER: dario       # Nuevo usuario
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql


  api:
    image: api
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

networks:
  spring-network:
volumes:
  mysql-volume:
